#spring.datasource.url=jdbc:mysql://localhost:3306/classroom_engagement?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
#spring.datasource.username=root
#spring.datasource.password=Anbu@2135
#spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

# JWT Configuration
jwt.secret=70617373776f72645f7365637265745f6b65795f6c6f6e675f656e6f7567685f666f725f736861323536
jwt.expiration=86400000

server.port=8080
spring.main.allow-bean-definition-overriding=true
spring.main.allow-circular-references=true
